List ProductDetail=[
  {
    "productName":"Chemex India Estates Blend",
    "category":"drink",
    "size":"short",
    "celsius":"125 Kcal",
    "description":"Chemex is a hybrid of pour over which is a drip brew and French press which is a full immersion brew and produces a clean and flavourful cup. Brewed with India Estates Blend Coffee",
    "price":283.50,
    "productNo":1,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Chemex Italian Roast",
    "category":"drink",
    "size":"tall",
    "celsius":"205 Kcal",
    "description":"Chemex is a hybrid of pour over which is a drip brew and French press which is a full immersion brew and produces a clean and flavourful cup. Brewed with India Roast Coffee",
    "price":295.50,
    "productNo":2,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour over Diwali Blend",
    "category":"drink",
    "size":"tall",
    "celsius":"0 Kcal",
    "description":"Pour over is a beautiful simple and accessible way to brew a single cup of coffee with clean, fully developed flavour and body. Brewed with Diwali Blend Coffee",
    "price":246.74,
    "productNo":3,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Espresso Roast Blend",
    "category":"drink",
    "size":"tall",
    "celsius":"100 Kcal",
    "description":"Chemex is a hybrid of pour over which is a drip brew and French press which is a full immersion brew and produces a clean and flavourful cup. Brewed with Espresso Roast Blend",
    "price":283.50,
    "productNo":4,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"French Press Blonde Roast",
    "category":"drink",
    "size":"short",
    "celsius":"125 Kcal",
    "description":"Blonde Roast French Press",
    "price":309.09,
    "productNo":5,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Siphon - Sumatra Dark Roast",
    "category":"drink",
    "size":"tall",
    "celsius":"90 Kcal",
    "description":"The siphon is a visually stunning brewing method that uses vacuum filtration to push extremely hot water through a bed of freshly ground coffee. Thanks to a paper filter and a relatively quick extraction time, this technique creates an uncommonly nuanced and delicate cup that mesmerizes the senses. Brewed with Sumatra coffee.",
    "price":383.25,
    "productNo":6,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Siphon - Kenya Roast",
    "category":"drink",
    "size":"short",
    "celsius":"95 Kcal",
    "description":"The siphon is a visually stunning brewing method that uses vacuum filtration to push extremely hot water through a bed of freshly ground coffee. Thanks to a paper filter and a relatively quick extraction time, this technique creates an uncommonly nuanced and delicate cup that mesmerizes the senses. Brewed with Kenya coffee",
    "price":383.25,
    "productNo":7,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },

  {
    //ch
    "productName":"Siphon - India Estates Blend",
    "category":"drink",
    "size":"tall",
    "celsius":"169 Kcal",
    "description":"The India Estates Blend is a rich and aromatic coffee that showcases the diverse and robust flavors of Indian coffee beans. This blend offers a harmonious balance of boldness and subtle sweetness, making it perfect for a siphon brew method, which enhances its nuanced flavors.",
    "price":383.50,
    "productNo":8,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    //ch
    "productName":"Siphon - Italian Roast",
    "category":"drink",
    "size":"short",
    "celsius":"50 Kcal",
    "description":"Italian Roast coffee is known for its deep, dark, and robust flavor profile with smoky, caramelized notes. This roast level brings out a rich intensity that pairs perfectly with the siphon brewing method, which enhances its bold and complex flavors.",
    "price":383.29,
    "productNo":9,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Siphon - Blonde Roast",
    "category":"drink",
    "size":"short",
    "celsius":"0 Kcal",
    "description":"Blonde Roast coffee is characterized by its light, delicate flavors and higher acidity compared to darker roasts. This roast preserves the origin flavors of the beans, making it ideal for a siphon brew method, which enhances its bright, nuanced notes.",
    "price":389.50,
    "productNo":10,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Filter Coffee",
    "category":"drink",
    "size":"short",
    "celsius":"189 Kcal",
    "description":"Introducing the new small size from Starbucks - Picco Filter Coffee Your favorite South Indian filter coffee prepared using a blend of our medium and dark roast coffees. Unreasonably perfect",
    "price":220.09,
    "productNo":11,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour Over India Estates Blend",
    "category":"drink",
    "size":"short",
    "celsius":"0 Kcal",
    "description":"Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with India Estates Blend.",
    "price":262.50,
    "productNo":12,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },

  {
    "productName":"French Press Brazil Carmo De Minas",
    "category":"drink",
    "size":"tall",
    "celsius":"200 Kcal",
    "description":"Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a French Press to extract the coffee's full flavours while retaining precious natural oils, resulting in a brew with a thick and rich consistency.",
    "price":360.50,
    "productNo":13,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Siphon Brazil Carmo De Minas",
    "category":"drink",
    "size":"short",
    "celsius":"150 Kcal",
    "description":"Craft meets science when our Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture is brewed in a Siphon to create a visually stunning coffee experience using vacuum filtration.",
    "price":414.90,
    "productNo":14,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Chemex Brazil Carmo De Minas",
    "category":"drink",
    "size":"tall",
    "celsius":"100 Kcal",
    "description":"Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a Chemex to produce a clean and flavourful cup.",
    "price":305.50,
    "productNo":15,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour Over Brazil Carmo De Minas",
    "category":"drink",
    "size":"short",
    "celsius":"150 Kcal",
    "description":"Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a Pour Over to produce a clean and flavourful cup with a fully developed body.",
    "price":283.50,
    "productNo":16,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Iced Pour Over Brazil Carmo De Minas",
    "category":"drink",
    "size":"tall",
    "celsius":"250 Kcal",
    "description":"Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a Pour Over to produce a clean and flavourful cup with a fully developed body. Served Iced.",
    "price":320.50,
    "productNo":17,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour Over Sumatra",
    "category":"drink",
    "size":"short",
    "celsius":"203 Kcal",
    "description":"Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Sumatra Roast. Short: 237 ML, 0 kcal, Tall: 354 ML, 0 kcal, Grande: 473 ML, 0 kcal, Venti: 591 ML, 0 kcal",
    "price":283.50,
    "productNo":18,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"French Press Kenya",
    "category":"drink",
    "size":"tall",
    "celsius":"0 Kcal",
    "description":"Brewing with a coffee press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavor while giving it a consistency that’s thick and Rich in flavour. Brewed with Kenya Roast. 473 ML, 0 kcal",
    "price":336.50,
    "productNo":19,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour Over - Kenya Blend",
    "category":"drink",
    "size":"short",
    "celsius":"102 Kcal",
    "description":"Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Kenya Roast.",
    "price":283.50,
    "productNo":20,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour Over - Italian Blend",
    "category":"drink",
    "size":"short",
    "celsius":"250 Kcal",
    "description":"Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Italian Roast.",
    "price":283.75,
    "productNo":21,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"French Press - Sumatra Blend",
    "category":"drink",
    "size":"tall",
    "celsius":"130 Kcal",
    "description":"Brewing with a French press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavor while giving it a consistency that’s thick and rich in flavour. Brewed with Sumatra Blend.",
    "price":336.75,
    "productNo":22,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"French Press - Kenya",
    "category":"drink",
    "size":"short",
    "celsius":"150 Kcal",
    "description":"Brewing with a French press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavour while giving it a consistency that’s thick and rich. Brewed with Kenya Blend.",
    "price":370.75,
    "productNo":23,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour over Italian roast",
    "category":"drink",
    "size":"short",
    "celsius":"0 Kcal",
    "description":"Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Italian Roast. Short: 237 ML, 0 kcal, Tall: 354 ML, 0 kcal, Grande: 473 ML, 0 kcal, Venti: 591 ML, 0 kcal",
    "price":283.75,
    "productNo":24,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"French Press - Italian",
    "category":"drink",
    "size":"tall",
    "celsius":"0 Kcal",
    "description":"Brewing with a French press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavour while giving it a consistency that’s thick and rich. Brewed with French italian.",
    "price":325.75,
    "productNo":25,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Pour Over Peru Chunqui",
    "category":"drink",
    "size":"short",
    "celsius":"0 Kcal",
    "description":"Starbucks® Single-Origin Peru Chunqui with bright notes of lemon verbena, dusted cocoa almond mouthfeel and sweetness, brewed using a pour over.",
    "price":299.25,
    "productNo":26,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"Siphon Peru Chunqui",
    "category":"drink",
    "size":"tall",
    "celsius":"0 Kcal",
    "description":"Starbucks® Single-Origin Peru Chunqui with bright notes of lemon verbena, dusted cocoa almond mouthfeel and sweetness, brewed using a Siphon.",
    "price":372.75,
    "productNo":27,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
  {
    "productName":"French Press Peru Chunqui",
    "category":"drink",
    "size":"short",
    "celsius":"0 Kcal",
    "description":"Starbucks® Single-Origin Peru Chunqui with bright notes of lemon verbena, dusted cocoa almond mouthfeel and sweetness, brewed using a French Press.",
    "price":330.75,
    "productNo":28,
    "ingredients":"milk",
    "veg_nonveg":"veg",
  },
];