List ProductDetail = [
  {
    "productName": "Chemex India Estates Blend",
    "category": "drink",
    // 'type':'',
    // 'like':false,
    "size": "short",
    "celsius": "125 Kcal",
    "description":
        "Chemex is a hybrid of pour over which is a drip brew and French press which is a full immersion brew and produces a clean and flavourful cup. Brewed with India Estates Blend Coffee",
    "price": 283.50,
    "productNo": 1,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Chemex Italian Roast",
    "category": "drink",
    "size": "tall",
    "celsius": "205 Kcal",
    "description":
        "Chemex is a hybrid of pour over which is a drip brew and French press which is a full immersion brew and produces a clean and flavourful cup. Brewed with India Roast Coffee",
    "price": 295.50,
    "productNo": 2,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour over Diwali Blend",
    "category": "drink",
    "size": "tall",
    "celsius": "0 Kcal",
    "description":
        "Pour over is a beautiful simple and accessible way to brew a single cup of coffee with clean, fully developed flavour and body. Brewed with Diwali Blend Coffee",
    "price": 246.74,
    "productNo": 3,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Espresso Roast Blend",
    "category": "drink",
    "size": "tall",
    "celsius": "100 Kcal",
    "description":
        "Chemex is a hybrid of pour over which is a drip brew and French press which is a full immersion brew and produces a clean and flavourful cup. Brewed with Espresso Roast Blend",
    "price": 283.50,
    "productNo": 4,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "French Press Blonde Roast",
    "category": "drink",
    "size": "short",
    "celsius": "125 Kcal",
    "description": "Blonde Roast French Press",
    "price": 309.09,
    "productNo": 5,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Siphon - Sumatra Dark Roast",
    "category": "drink",
    "size": "tall",
    "celsius": "90 Kcal",
    "description":
        "The siphon is a visually stunning brewing method that uses vacuum filtration to push extremely hot water through a bed of freshly ground coffee. Thanks to a paper filter and a relatively quick extraction time, this technique creates an uncommonly nuanced and delicate cup that mesmerizes the senses. Brewed with Sumatra coffee.",
    "price": 383.25,
    "productNo": 6,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Siphon - Kenya Roast",
    "category": "drink",
    "size": "short",
    "celsius": "95 Kcal",
    "description":
        "The siphon is a visually stunning brewing method that uses vacuum filtration to push extremely hot water through a bed of freshly ground coffee. Thanks to a paper filter and a relatively quick extraction time, this technique creates an uncommonly nuanced and delicate cup that mesmerizes the senses. Brewed with Kenya coffee",
    "price": 383.25,
    "productNo": 7,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },

  {
    //ch
    "productName": "Siphon - India Estates Blend",
    "category": "drink",
    "size": "tall",
    "celsius": "169 Kcal",
    "description":
        "The India Estates Blend is a rich and aromatic coffee that showcases the diverse and robust flavors of Indian coffee beans. This blend offers a harmonious balance of boldness and subtle sweetness, making it perfect for a siphon brew method, which enhances its nuanced flavors.",
    "price": 383.50,
    "productNo": 8,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    //ch
    "productName": "Siphon - Italian Roast",
    "category": "drink",
    "size": "short",
    "celsius": "50 Kcal",
    "description":
        "Italian Roast coffee is known for its deep, dark, and robust flavor profile with smoky, caramelized notes. This roast level brings out a rich intensity that pairs perfectly with the siphon brewing method, which enhances its bold and complex flavors.",
    "price": 383.29,
    "productNo": 9,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Siphon - Blonde Roast",
    "category": "drink",
    "size": "short",
    "celsius": "0 Kcal",
    "description":
        "Blonde Roast coffee is characterized by its light, delicate flavors and higher acidity compared to darker roasts. This roast preserves the origin flavors of the beans, making it ideal for a siphon brew method, which enhances its bright, nuanced notes.",
    "price": 389.50,
    "productNo": 10,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Filter Coffee",
    "category": "drink",
    "size": "short",
    "celsius": "189 Kcal",
    "description":
        "Introducing the new small size from Starbucks - Picco Filter Coffee Your favorite South Indian filter coffee prepared using a blend of our medium and dark roast coffees. Unreasonably perfect",
    "price": 220.09,
    "productNo": 11,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour Over India Estates Blend",
    "category": "drink",
    "size": "short",
    "celsius": "0 Kcal",
    "description":
        "Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with India Estates Blend.",
    "price": 262.50,
    "productNo": 12,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },

  {
    "productName": "French Press Brazil Carmo De Minas",
    "category": "drink",
    "size": "tall",
    "celsius": "200 Kcal",
    "description":
        "Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a French Press to extract the coffee's full flavours while retaining precious natural oils, resulting in a brew with a thick and rich consistency.",
    "price": 360.50,
    "productNo": 13,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Siphon Brazil Carmo De Minas",
    "category": "drink",
    "size": "short",
    "celsius": "150 Kcal",
    "description":
        "Craft meets science when our Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture is brewed in a Siphon to create a visually stunning coffee experience using vacuum filtration.",
    "price": 414.90,
    "productNo": 14,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Chemex Brazil Carmo De Minas",
    "category": "drink",
    "size": "tall",
    "celsius": "100 Kcal",
    "description":
        "Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a Chemex to produce a clean and flavourful cup.",
    "price": 305.50,
    "productNo": 15,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour Over Brazil Carmo De Minas",
    "category": "drink",
    "size": "short",
    "celsius": "150 Kcal",
    "description":
        "Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a Pour Over to produce a clean and flavourful cup with a fully developed body.",
    "price": 283.50,
    "productNo": 16,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Pour Over Brazil Carmo De Minas",
    "category": "drink",
    "size": "tall",
    "celsius": "250 Kcal",
    "description":
        "Single Origin Sun Dried Brazil Carmo De Minas with notes of tropical fruits, sweet hazelnuts and a smooth caramelly texture brewed in a Pour Over to produce a clean and flavourful cup with a fully developed body. Served Iced.",
    "price": 320.50,
    "productNo": 17,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour Over Sumatra",
    "category": "drink",
    "size": "short",
    "celsius": "203 Kcal",
    "description":
        "Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Sumatra Roast. Short: 237 ML, 0 kcal, Tall: 354 ML, 0 kcal, Grande: 473 ML, 0 kcal, Venti: 591 ML, 0 kcal",
    "price": 283.50,
    "productNo": 18,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "French Press Kenya",
    "category": "drink",
    "size": "tall",
    "celsius": "0 Kcal",
    "description":
        "Brewing with a coffee press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavor while giving it a consistency that’s thick and Rich in flavour. Brewed with Kenya Roast. 473 ML, 0 kcal",
    "price": 336.50,
    "productNo": 19,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour Over - Kenya Blend",
    "category": "drink",
    "size": "short",
    "celsius": "102 Kcal",
    "description":
        "Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Kenya Roast.",
    "price": 283.50,
    "productNo": 20,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour Over - Italian Blend",
    "category": "drink",
    "size": "short",
    "celsius": "250 Kcal",
    "description":
        "Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Italian Roast.",
    "price": 283.75,
    "productNo": 21,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "French Press - Sumatra Blend",
    "category": "drink",
    "size": "tall",
    "celsius": "130 Kcal",
    "description":
        "Brewing with a French press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavor while giving it a consistency that’s thick and rich in flavour. Brewed with Sumatra Blend.",
    "price": 336.75,
    "productNo": 22,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "French Press - Kenya",
    "category": "drink",
    "size": "short",
    "celsius": "150 Kcal",
    "description":
        "Brewing with a French press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavour while giving it a consistency that’s thick and rich. Brewed with Kenya Blend.",
    "price": 370.75,
    "productNo": 23,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour over Italian roast",
    "category": "drink",
    "size": "short",
    "celsius": "0 Kcal",
    "description":
        "Pour-over is a beautifully simple and accessible way to brew a single cup of coffee with clean, fully developed flavor and body. Brewed with Italian Roast. Short: 237 ML, 0 kcal, Tall: 354 ML, 0 kcal, Grande: 473 ML, 0 kcal, Venti: 591 ML, 0 kcal",
    "price": 283.75,
    "productNo": 24,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "French Press - Italian",
    "category": "drink",
    "size": "tall",
    "celsius": "0 Kcal",
    "description":
        "Brewing with a French press retains the precious natural oils that paper filters absorb, and extracts the coffee’s full flavour while giving it a consistency that’s thick and rich. Brewed with French italian.",
    "price": 325.75,
    "productNo": 25,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pour Over Peru Chunqui",
    "category": "drink",
    "size": "short",
    "celsius": "0 Kcal",
    "description":
        "Starbucks® Single-Origin Peru Chunqui with bright notes of lemon verbena, dusted cocoa almond mouthfeel and sweetness, brewed using a pour over.",
    "price": 299.25,
    "productNo": 26,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Siphon Peru Chunqui",
    "category": "drink",
    "size": "tall",
    "celsius": "0 Kcal",
    "description":
        "Starbucks® Single-Origin Peru Chunqui with bright notes of lemon verbena, dusted cocoa almond mouthfeel and sweetness, brewed using a Siphon.",
    "price": 372.75,
    "productNo": 27,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "French Press Peru Chunqui",
    "category": "drink",
    "size": "short",
    "celsius": "0 Kcal",
    "description":
        "Starbucks® Single-Origin Peru Chunqui with bright notes of lemon verbena, dusted cocoa almond mouthfeel and sweetness, brewed using a French Press.",
    "price": 330.75,
    "productNo": 28,
    "ingredients": "milk",
    "veg_nonveg": "veg",
  },
  ////////////////////////////////////////////////////////
  /*Dipesh cold brew*/
  {
    "productName": "Cold Brew Classic",
    "category": "cold brew",
    "size": "short",
    "celsius": "100 Kcal",
    "description":
        "Cold Brew Classic is a smooth and refreshing cold coffee brewed with premium beans.",
    "price": 250.00,
    "productNo": 1,
    "ingredients": "Premium Coffee Beans, Water",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Vanilla",
    "category": "cold brew",
    "size": "medium",
    "celsius": "120 Kcal",
    "description":
        "Cold Brew Vanilla offers a hint of vanilla to the classic cold brew for a delightful twist.",
    "price": 300.00,
    "productNo": 2,
    "ingredients": "Premium Coffee Beans, Water, Vanilla Extract",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Caramel",
    "category": "cold brew",
    "size": "large",
    "celsius": "150 Kcal",
    "description":
        "Cold Brew Caramel combines the rich flavor of caramel with cold brew coffee for a sweet treat.",
    "price": 350.00,
    "productNo": 3,
    "ingredients": "Premium Coffee Beans, Water, Caramel Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Hazelnut",
    "category": "cold brew",
    "size": "short",
    "celsius": "110 Kcal",
    "description":
        "Cold Brew Hazelnut brings a nutty flavor to cold brew coffee for a unique experience.",
    "price": 275.00,
    "productNo": 4,
    "ingredients": "Premium Coffee Beans, Water, Hazelnut Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Mocha",
    "category": "cold brew",
    "size": "medium",
    "celsius": "180 Kcal",
    "description":
        "Cold Brew Mocha blends cold brew coffee with chocolate for a decadent drink.",
    "price": 400.00,
    "productNo": 5,
    "ingredients": "Premium Coffee Beans, Water, Chocolate Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Almond",
    "category": "cold brew",
    "size": "large",
    "celsius": "140 Kcal",
    "description":
        "Cold Brew Almond has a subtle almond flavor that complements the smooth cold brew coffee.",
    "price": 375.00,
    "productNo": 6,
    "ingredients": "Premium Coffee Beans, Water, Almond Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Coconut",
    "category": "cold brew",
    "size": "short",
    "celsius": "130 Kcal",
    "description":
        "Cold Brew Coconut infuses coconut flavor into cold brew coffee for a tropical touch.",
    "price": 290.00,
    "productNo": 7,
    "ingredients": "Premium Coffee Beans, Water, Coconut Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Cinnamon",
    "category": "cold brew",
    "size": "medium",
    "celsius": "110 Kcal",
    "description":
        "Cold Brew Cinnamon adds a hint of cinnamon spice to cold brew coffee.",
    "price": 310.00,
    "productNo": 8,
    "ingredients": "Premium Coffee Beans, Water, Cinnamon Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Maple",
    "category": "cold brew",
    "size": "large",
    "celsius": "160 Kcal",
    "description":
        "Cold Brew Maple combines the sweetness of maple syrup with cold brew coffee.",
    "price": 420.00,
    "productNo": 9,
    "ingredients": "Premium Coffee Beans, Water, Maple Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Peppermint",
    "category": "cold brew",
    "size": "short",
    "celsius": "105 Kcal",
    "description":
        "Cold Brew Peppermint offers a refreshing minty twist to cold brew coffee.",
    "price": 265.00,
    "productNo": 10,
    "ingredients": "Premium Coffee Beans, Water, Peppermint Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Lavender",
    "category": "cold brew",
    "size": "medium",
    "celsius": "115 Kcal",
    "description":
        "Cold Brew Lavender provides a floral hint to the smooth cold brew coffee.",
    "price": 340.00,
    "productNo": 11,
    "ingredients": "Premium Coffee Beans, Water, Lavender Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Rose",
    "category": "cold brew",
    "size": "large",
    "celsius": "145 Kcal",
    "description":
        "Cold Brew Rose adds a delicate rose flavor to cold brew coffee for a unique experience.",
    "price": 450.00,
    "productNo": 12,
    "ingredients": "Premium Coffee Beans, Water, Rose Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Spiced",
    "category": "cold brew",
    "size": "short",
    "celsius": "125 Kcal",
    "description":
        "Cold Brew Spiced includes a mix of spices to add warmth to cold brew coffee.",
    "price": 280.00,
    "productNo": 13,
    "ingredients": "Premium Coffee Beans, Water, Spice Blend",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Citrus",
    "category": "cold brew",
    "size": "medium",
    "celsius": "135 Kcal",
    "description":
        "Cold Brew Citrus infuses citrus notes into cold brew coffee for a refreshing twist.",
    "price": 320.00,
    "productNo": 14,
    "ingredients": "Premium Coffee Beans, Water, Citrus Extract",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Berry",
    "category": "cold brew",
    "size": "large",
    "celsius": "155 Kcal",
    "description":
        "Cold Brew Berry combines berry flavors with cold brew coffee for a fruity delight.",
    "price": 375.00,
    "productNo": 15,
    "ingredients": "Premium Coffee Beans, Water, Berry Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Toffee",
    "category": "cold brew",
    "size": "short",
    "celsius": "160 Kcal",
    "description":
        "Cold Brew Toffee offers a rich toffee flavor to the smooth cold brew coffee.",
    "price": 295.00,
    "productNo": 16,
    "ingredients": "Premium Coffee Beans, Water, Toffee Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Chocolate Mint",
    "category": "cold brew",
    "size": "medium",
    "celsius": "175 Kcal",
    "description":
        "Cold Brew Chocolate Mint blends chocolate and mint flavors with cold brew coffee.",
    "price": 350.00,
    "productNo": 17,
    "ingredients": "Premium Coffee Beans, Water, Chocolate Mint Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Ginger",
    "category": "cold brew",
    "size": "large",
    "celsius": "125 Kcal",
    "description":
        "Cold Brew Ginger adds a zesty ginger flavor to cold brew coffee for a spicy kick.",
    "price": 410.00,
    "productNo": 18,
    "ingredients": "Premium Coffee Beans, Water, Ginger Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Cardamom",
    "category": "cold brew",
    "size": "short",
    "celsius": "110 Kcal",
    "description":
        "Cold Brew Cardamom brings a unique cardamom flavor to the smooth cold brew coffee.",
    "price": 270.00,
    "productNo": 19,
    "ingredients": "Premium Coffee Beans, Water, Cardamom Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew Nutmeg",
    "category": "cold brew",
    "size": "medium",
    "celsius": "140 Kcal",
    "description":
        "Cold Brew Nutmeg adds a warm nutmeg flavor to cold brew coffee for a cozy drink.",
    "price": 330.00,
    "productNo": 20,
    "ingredients": "Premium Coffee Beans, Water, Nutmeg Syrup",
    "veg_nonveg": "veg",
  },
  /*Dipesh cappuccino*/
  {
    "productName": "Cappuccino",
    "category": "other beverages",
    "size": "short",
    "celsius": "150 Kcal",
    "description":
        "A classic Italian coffee drink that is traditionally prepared with equal parts double espresso, steamed milk, and steamed milk foam.",
    "price": 250.00,
    "productNo": 11,
    "ingredients": "Espresso, Steamed Milk, Milk Foam",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Latte",
    "category": "other beverages",
    "size": "medium",
    "celsius": "190 Kcal",
    "description":
        "A coffee drink made with espresso and steamed milk, known for its smooth and creamy texture.",
    "price": 300.00,
    "productNo": 12,
    "ingredients": "Espresso, Steamed Milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Mocha",
    "category": "other beverages",
    "size": "large",
    "celsius": "250 Kcal",
    "description":
        "A chocolate-flavored variant of a caffè latte, made with espresso, hot milk, and added chocolate.",
    "price": 350.00,
    "productNo": 13,
    "ingredients": "Espresso, Steamed Milk, Chocolate Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Americano",
    "category": "other beverages",
    "size": "short",
    "celsius": "80 Kcal",
    "description":
        "A style of coffee prepared by brewing espresso with added hot water, giving it a similar strength but different flavor from traditional drip coffee.",
    "price": 220.00,
    "productNo": 14,
    "ingredients": "Espresso, Hot Water",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Flat White",
    "category": "other beverages",
    "size": "medium",
    "celsius": "180 Kcal",
    "description":
        "A coffee drink consisting of espresso with microfoam (steamed milk with fine, velvety bubbles) poured over it.",
    "price": 280.00,
    "productNo": 15,
    "ingredients": "Espresso, Microfoam Milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Macchiato",
    "category": "other beverages",
    "size": "short",
    "celsius": "100 Kcal",
    "description":
        "An espresso coffee drink with a small amount of milk, usually foamed.",
    "price": 230.00,
    "productNo": 16,
    "ingredients": "Espresso, Foamed Milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Affogato",
    "category": "other beverages",
    "size": "short",
    "celsius": "220 Kcal",
    "description":
        "A coffee-based dessert, usually a scoop of vanilla ice cream topped or drowned with a shot of hot espresso.",
    "price": 300.00,
    "productNo": 17,
    "ingredients": "Espresso, Vanilla Ice Cream",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cold Brew",
    "category": "other beverages",
    "size": "large",
    "celsius": "120 Kcal",
    "description":
        "Coffee made by steeping coarse-ground beans in room-temperature water for an extended period and served chilled.",
    "price": 350.00,
    "productNo": 18,
    "ingredients": "Coarse-ground Coffee, Water",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Latte",
    "category": "other beverages",
    "size": "large",
    "celsius": "180 Kcal",
    "description":
        "A cold coffee drink made with espresso and chilled milk, served over ice.",
    "price": 330.00,
    "productNo": 19,
    "ingredients": "Espresso, Milk, Ice",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Mocha",
    "category": "other beverages",
    "size": "large",
    "celsius": "250 Kcal",
    "description":
        "A cold coffee drink made with espresso, chilled milk, and chocolate syrup, served over ice.",
    "price": 370.00,
    "productNo": 20,
    "ingredients": "Espresso, Milk, Chocolate Syrup, Ice",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Caramel Frappuccino",
    "category": "other beverages",
    "size": "large",
    "celsius": "300 Kcal",
    "description":
        "A blended beverage made with coffee, milk, ice, and caramel syrup, topped with whipped cream.",
    "price": 400.00,
    "productNo": 21,
    "ingredients": "Coffee, Milk, Ice, Caramel Syrup, Whipped Cream",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Green Tea Latte",
    "category": "other beverages",
    "size": "medium",
    "celsius": "200 Kcal",
    "description":
        "A creamy beverage made with matcha green tea and steamed milk.",
    "price": 320.00,
    "productNo": 22,
    "ingredients": "Matcha Green Tea, Steamed Milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Chai Latte",
    "category": "other beverages",
    "size": "medium",
    "celsius": "210 Kcal",
    "description":
        "A spiced tea beverage made with black tea, steamed milk, and a blend of spices.",
    "price": 310.00,
    "productNo": 23,
    "ingredients": "Black Tea, Steamed Milk, Spices",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Chai Latte",
    "category": "other beverages",
    "size": "large",
    "celsius": "220 Kcal",
    "description":
        "A cold, spiced tea beverage made with black tea, chilled milk, and a blend of spices, served over ice.",
    "price": 330.00,
    "productNo": 24,
    "ingredients": "Black Tea, Chilled Milk, Spices, Ice",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Matcha Frappuccino",
    "category": "other beverages",
    "size": "large",
    "celsius": "280 Kcal",
    "description":
        "A blended beverage made with matcha green tea, milk, and ice, topped with whipped cream.",
    "price": 420.00,
    "productNo": 25,
    "ingredients": "Matcha Green Tea, Milk, Ice, Whipped Cream",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Turmeric Latte",
    "category": "other beverages",
    "size": "medium",
    "celsius": "190 Kcal",
    "description":
        "A warming beverage made with steamed milk and turmeric, known for its anti-inflammatory properties.",
    "price": 310.00,
    "productNo": 26,
    "ingredients": "Turmeric, Steamed Milk",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Pumpkin Spice Latte",
    "category": "other beverages",
    "size": "medium",
    "celsius": "210 Kcal",
    "description":
        "A seasonal favorite, made with espresso, steamed milk, pumpkin spice flavoring, and topped with whipped cream.",
    "price": 350.00,
    "productNo": 27,
    "ingredients": "Espresso, Steamed Milk, Pumpkin Spice Syrup, Whipped Cream",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Peppermint Mocha",
    "category": "other beverages",
    "size": "large",
    "celsius": "280 Kcal",
    "description":
        "A holiday favorite, made with espresso, steamed milk, chocolate, and peppermint flavoring.",
    "price": 370.00,
    "productNo": 28,
    "ingredients": "Espresso, Steamed Milk, Chocolate Syrup, Peppermint Syrup",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Espresso Con Panna",
    "category": "other beverages",
    "size": "short",
    "celsius": "120 Kcal",
    "description": "A shot of espresso topped with a dollop of whipped cream.",
    "price": 260.00,
    "productNo": 29,
    "ingredients": "Espresso, Whipped Cream",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Hot Chocolate",
    "category": "other beverages",
    "size": "large",
    "celsius": "290 Kcal",
    "description":
        "A rich and creamy beverage made with steamed milk and chocolate, topped with whipped cream.",
    "price": 310.00,
    "productNo": 30,
    "ingredients": "Steamed Milk, Chocolate Syrup, Whipped Cream",
    "veg_nonveg": "veg",
  },
  /*Ravi espresso*/
  {
    "productName": "Iced Mocha Cookie Crumble Latte",
    "category": "drink",
    "size": "TALL",
    "celsius": "386 Kcal",
    "description":
        "Our Mocha Cookie crumble Latte is a deliciously flavoured mocha indulgence - Hot coffee meets chocolate and cookies for a perfect combination. Served over ice.",
    "price": 477.75,
    "productNo": 1,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Mocha Cookie Crumble Latte",
    "category": "drink",
    "size": "SHORT",
    "celsius": "294 kcal",
    "description":
        "Our Mocha Cookie crumble Latte is a deliciously flavoured mocha indulgence - Hot coffee meets chocolate and cookies for a perfect combination",
    "price": 435.75,
    "productNo": 2,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Stardust Macchiato",
    "category": "drink",
    "size": "SHORT",
    "description":
        "Super smooth and creamy vanilla half and half crowned with sweet and subtle cold foam, marked with an intense ristretto shot and cocoa dust",
    "price": 414.75,
    "productNo": 3,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Stardust Macchiato",
    "category": "drink",
    "size": "TALL",
    "description":
        "Super smooth and creamy vanilla half and half crowned with sweet and subtle cold foam, marked with an intense ristretto shot and cocoa dust. Served over ice.",
    "price": 456.75,
    "productNo": 4,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Caffè Americano",
    "category": "drink",
    "size": "SHORT",
    "celsius": "0 Kcal",
    "description":
        "Rich, full-bodied espresso with hot water in true European style. Energy per Serving Size - Nil , Allergen - Nil.",
    "price": 278.25,
    "productNo": 5,
    "ingredients": "BREWED COFFEE",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Caffè Mocha",
    "category": "drink",
    "size": "SHORT",
    "celsius": "232 Kcal",
    "description":
        "We combine our Rich in flavour, full-bodied espresso with bittersweet mocha sauce and steamed milk. The classic coffee drink to satisfy your sweet tooth. Hot - Short (237ml) - 232 kcal / Tall (354ml) - 335.7 kcal / Grande (473ml) - 391.1 kcal / Venti (591ml) 472.7 kcal Allergen - Contains Milk An average active adult requires 2000 kcal energy per day, however, calorie needs may vary.",
    "price": 341.25,
    "productNo": 6,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cappuccino",
    "category": "drink",
    "size": "SHORT",
    "celsius": "104 Kcal",
    "description":
        "Dark, Rich in flavour espresso lies in wait under a smoothed and stretched layer of thick foam. It's truly the height of our baristas' craft.",
    "price": 299.25,
    "productNo": 7,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Caffe Latte",
    "category": "drink",
    "size": "SHORT",
    "celsius": "104 Kcal",
    "description":
        "Our dark, Rich in flavour espresso balanced with steamed milk and a light layer of foam. A perfect coffee warm up.",
    "price": 304.50,
    "productNo": 8,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Caramel Macchiato",
    "category": "drink",
    "size": "SHORT",
    "celsius": "162 Kcal",
    "description":
        "Freshly steamed milk with vanilla-flavored syrup is marked with espresso and topped with caramel drizzle.",
    "price": 362.25,
    "productNo": 9,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Chocolate Cappuccino",
    "category": "drink",
    "size": "SHORT",
    "celsius": "150 Kcal",
    "description":
        "Dark, Rich in flavour espresso and bittersweet cocoa lies in wait under a smoothed and stretched layer of thick foam.",
    "price": 372.75,
    "productNo": 10,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Chocolate Cortado",
    "category": "drink",
    "size": "PER SERVE",
    "celsius": "88 Kcal",
    "description":
        "A perfect espresso shot and mocha sauce, topped with steamed milk.",
    "price": 351.75,
    "productNo": 11,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Cortado",
    "category": "drink",
    "size": "PER SERVE",
    "celsius": "72 Kcal",
    "description": "A perfect espresso shot topped with steamed milk.",
    "price": 294.00,
    "productNo": 12,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Doppio Espresso",
    "category": "drink",
    "size": "PER SERVE",
    "celsius": "0 Kcal",
    "description":
        "Our smooth signature Espresso Roast and its caramelly sweetness is at the very heart of everything we do.",
    "price": 278.25,
    "productNo": 13,
    "ingredients": "BREWED COFFEE",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Flat White",
    "category": "drink",
    "size": "SHORT",
    "celsius": "104 Kcal",
    "description":
        "Expertly steamed milk poured over shots of ristretto and finished with a Starbucks signature dot.",
    "price": 330.75,
    "productNo": 14,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Hazelnut Cortado",
    "category": "drink",
    "size": "PER SERVE",
    "celsius": "76 Kcal",
    "description":
        "A perfect espresso shot and hazelnut syrup, topped with steamed milk.",
    "price": 351.75,
    "productNo": 15,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Caffè Americano",
    "category": "drink",
    "size": "TALL",
    "celsius": "0 Kcal",
    "description":
        "Espresso shots are topped with water to produce a light layer of crema, then served over ice.",
    "price": 315.00,
    "productNo": 16,
    "ingredients": "BREWED COFFEE",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Caffè Latte",
    "category": "drink",
    "size": "TALL",
    "celsius": "122 Kcal",
    "description":
        "Our dark, Rich in flavour espresso is combined with milk and served over ice.",
    "price": 341.25,
    "productNo": 17,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Caffè Mocha",
    "category": "drink",
    "size": "TALL",
    "celsius": "291 Kcal",
    "description":
        "Espresso combined with bittersweet mocha sauce and milk and served over ice. Topped with whipped vanilla topping.",
    "price": 378,
    "productNo": 18,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Cappuccino",
    "category": "drink",
    "size": "TALL",
    "celsius": "214 Kcal",
    "description":
        "Signature Italian style Cappuccino with espresso shot, steamed milk and a thick layer of foam, served over ice.",
    "price": 336,
    "productNo": 19,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Chocolate Cappuccino",
    "category": "drink",
    "size": "TALL",
    "celsius": "161 Kcal",
    "description":
        "Signature Italian style Cappuccino with espresso shot, mocha sauce, steamed milk and a thick layer of foam, served over ice.",
    "price": 409.50,
    "productNo": 20,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced Velvet Vanilla Latte",
    "category": "drink",
    "size": "TALL",
    "celsius": "383 Kcal",
    "description":
        "Rich in texture, smooth, and creamy latte elevated with vanilla and a dairy twist – Half and half, served over ice.",
    "price": 435.75,
    "productNo": 21,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Solo Espresso",
    "category": "drink",
    "size": "PRE SERVE",
    "celsius": "0 Kcal",
    "description":
        "Our smooth signature Espresso Roast and its caramelly sweetness is at the very heart of everything we do.",
    "price": 262.50,
    "productNo": 22,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Iced White Mocha",
    "category": "drink",
    "size": "TALL",
    "celsius": "339 Kcal",
    "description":
        "Espresso combined with white mocha sauce and milk over ice. Topped with whipped vanilla topping.",
    "price": 388.50,
    "productNo": 23,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Vanilla Cortado",
    "category": "drink",
    "size": "PER SERVE",
    "celsius": "0 Kcal",
    "description":
        "A perfect espresso shot and vanilla syrup topped with steamed milk.",
    "price": 351.75,
    "productNo": 24,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "Velvet Vanilla Latte",
    "category": "drink",
    "size": "SHORT",
    "celsius": "280 Kcal",
    "description":
        "Our dark, Rich in flavour espresso balanced with vanilla flavored syrup, steamed half and half and a light layer of foam.",
    "price": 399.00,
    "productNo": 25,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
  {
    "productName": "White Chocolate Mocha",
    "category": "drink",
    "size": "SHORT",
    "celsius": "252 Kcal",
    "description":
    "Our signature espresso meets white chocolate sauce and steamed milk, then is finished off with whipped vanilla topping in this white chocolate delight.",
    "price": 351.75,
    "productNo": 26,
    "ingredients": "MILK",
    "veg_nonveg": "veg",
  },
];

List save = [ProductDetail];

List cartList = [];
List foodList = [
  {
    "productName": "Raisin Swirl",
    'type': 'Sandwiches & Wraps',
    //Sandwiches & Wraps,Croissants, Cookies & Desserts, Puffs & Pies, Bakery, Cakes

    'like': false,
    //Do not make any changes in this key or value [no change]
    'image': '',
    "category": "Cookie",
    //Veg, Non veg, Contains, Egg, Bakery,Cake, Dessert, Spicy ,Sweet,Healthy,
    "size": "Normal",
    "celsius": "85g/288 Kcal",
    "description":
        "Indulge in our delicious raisin swirl, crafted with a rich buttery melt-in-your-mouth texture and intense flavor. Inside, you'll find a soft center filled with a delightful blend of naturally sweet raisins.",
    "price": 367.50,
    "productNo": 1,
    "ingredients": "Milk Wheat Egg",
    "veg_nonveg": "Non Veg",
  },
];
List drinksList = [
  {
    "productName": "",
    'type': 'Sandwiches & Wraps',
    //Espresso , Frappuccino Blended Beverages, Other Beverages, Brewed Coffee, TEa, Cold Brew
    'like': false,
    //Do not make any changes in this key or value [no change]
    'image': '',
    "category": "Cookie",
    //Hot , Cold Milkshake Black, Blended, Caffeine free, Nitro,On Tap, Ice Cream ,Cream, Brew,Juice, Ice cream
    "size": "Normal",
    "celsius": "85g/288 Kcal",
    "description":
        "Indulge in our delicious raisin swirl, crafted with a rich buttery melt-in-your-mouth texture and intense flavor. Inside, you'll find a soft center filled with a delightful blend of naturally sweet raisins.",
    "price": 367.50,
    "productNo": 1,
    "ingredients": "Milk Wheat Egg",
    "veg_nonveg": "Non Veg",
  },
];
List merchandiseList = [
  {
    "productName": "",
    'type': 'Core Essential',
    //Core Essential , Seasonal Collection,Been There Series, Stainless Steel,Reusable Cups,Coaster,Cup
    'like': false,
    //Do not make any changes in this key or value [no change]
    'image': '',
    "category": "Mugs",
    //Mugs, Cups, Tumbles , Water Bottles , Accessories
    "size": "355ml",
    //427ml,355ml
    "celsius": "85g/288 Kcal",
    "description":
        "Indulge in our delicious raisin swirl, crafted with a rich buttery melt-in-your-mouth texture and intense flavor. Inside, you'll find a soft center filled with a delightful blend of naturally sweet raisins.",
    "price": 367.50,
    "productNo": 1,
  },
];
List coffeeAtHomeList = [
  {
    "productName": "",
    'like': false,
    //Do not make any changes in this key or value [no change]
    'image': '',
    "category": "Blend",
    //Blend , Blonde Roast, Dark Roast ,Medium Roast , Single Origin
    "veg_nonveg": "Non Veg",

    "description":
        "Indulge in our delicious raisin swirl, crafted with a rich buttery melt-in-your-mouth texture and intense flavor. Inside, you'll find a soft center filled with a delightful blend of naturally sweet raisins.",
    "price": 367.50,
    "productNo": 1,
  },
];
